x-shared-environment: &shared-environment
  # We set default values only for GitHub Actions' benefit. When we replace calls to
  # `docker compose run` with calls to `just`, then we can remove them.
  DB_HOST: postgis
  DB_NAME: ${DB_NAME:-openprescribing-test}
  DB_PASS: ${DB_PASS:-pass}
  DB_USER: ${DB_USER:-user}
  MAILGUN_API_KEY: ${MAILGUN_API_KEY:-mailgun_api_key}
  MAILGUN_WEBHOOK_PASS: ${MAILGUN_WEBHOOK_PASS:-mailgun_webhook_pass}
  MAILGUN_WEBHOOK_USER: ${MAILGUN_WEBHOOK_USER:-mailgun_webhook_user}
  SECRET_KEY: ${SECRET_KEY:-secret_key}

x-browserstacklocal: &browserstacklocal
  image: browserstack/local:latest
  # We disable the dashboard because 1) It's not that useful; and 2) We might want
  # browserstacklocal and browserstacklocal-test to run simultaneously (they have
  # different network namespaces). However, only the container that started first would
  # bind the dashboard to localhost; the container that started second would error.
  command: ["--key", "${BROWSERSTACK_ACCESS_KEY:-}", "--disable-dashboard"]

services:
  postgis:
    image: postgis/postgis:16-3.4
    environment:
      # These values are defined here as well as in justfile (DB_PASS, DB_USER,
      # DB_NAME). We accept a small amount of redundancy in return for decoupling this
      # service from other services.
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: openprescribing-test
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready; exit $(( $? != 0 ))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 5s

  browserstacklocal:
    <<: *browserstacklocal
    network_mode: "host"

  browserstacklocal-test:
    <<: *browserstacklocal

  test:
    image: ghcr.io/bennettoxford/openprescribing-py312-test:latest
    command: /bin/bash -c './scripts/docker_setup.sh && cd openprescribing && make test'
    environment:
      <<: *shared-environment
      DJANGO_SETTINGS_MODULE: openprescribing.settings.test
      BROWSER: ${BROWSER:-}
      TEST_SUITE: ${TEST_SUITE:-}
      GOOGLE_APPLICATION_CREDENTIALS: /code/google-credentials.json
      GITHUB_ACTIONS: ${GITHUB_ACTIONS:-}
      USE_BROWSERSTACK: ${USE_BROWSERSTACK:-}
      BROWSERSTACK_USERNAME: ${BROWSERSTACK_USERNAME:-}
      BROWSERSTACK_ACCESS_KEY: ${BROWSERSTACK_ACCESS_KEY:-}
      BROWSERSTACK_PROJECT_NAME: ${BROWSERSTACK_PROJECT_NAME:-}
      BROWSERSTACK_BUILD_NAME: ${BROWSERSTACK_BUILD_NAME:-}
      BROWSERSTACK_LOCAL_IDENTIFIER: ${BROWSERSTACK_LOCAL_IDENTIFIER:-}
    network_mode: "service:browserstacklocal-test"
    volumes:
      - .:/code
    depends_on:
      postgis:
        condition: service_healthy
      browserstacklocal-test:
        condition: service_started

  test-production:
    image: ghcr.io/bennettoxford/openprescribing-py312-base:latest
    command: /bin/bash -c './scripts/docker_setup.sh && cd openprescribing && python manage.py check --deploy'
    environment:
      <<: *shared-environment
      DJANGO_SETTINGS_MODULE: openprescribing.settings.production
    volumes:
      - .:/code
    depends_on:
      postgis:
        condition: service_healthy

  dev:
    image: ghcr.io/bennettoxford/openprescribing-py312-test:latest
    command: /bin/bash -c './scripts/docker_setup.sh &&  cd openprescribing && /bin/bash -l'
    environment:
      <<: *shared-environment
      DJANGO_SETTINGS_MODULE: openprescribing.settings.local
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      postgis:
        condition: service_healthy

volumes:
  postgis_data:
