services:

  postgis:
    image: postgis/postgis:16-3.4
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=openprescribing-test
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready; exit $(( $? != 0 ))" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 5s

  test:
    image: ghcr.io/bennettoxford/openprescribing-py312-test:latest
    command: /bin/bash -c './scripts/docker_setup.sh && cd openprescribing && make test'
    environment:
      - DJANGO_SETTINGS_MODULE=openprescribing.settings.test
      - BROWSER=${BROWSER:-placeholder}
      - TEST_SUITE=${TEST_SUITE:-placeholder}
      - GOOGLE_APPLICATION_CREDENTIALS=/code/google-credentials.json
      - GITHUB_ACTIONS=${GITHUB_ACTIONS:-}
      - BROWSERSTACK_USERNAME=${BROWSERSTACK_USERNAME:-placeholder}
      - BROWSERSTACK_ACCESS_KEY=${BROWSERSTACK_ACCESS_KEY:-placeholder}
      - BROWSERSTACK_PROJECT_NAME=${BROWSERSTACK_PROJECT_NAME:-placeholder}
      - BROWSERSTACK_BUILD_NAME=${BROWSERSTACK_BUILD_NAME:-placeholder}
      - BROWSERSTACK_LOCAL_IDENTIFIER=${BROWSERSTACK_LOCAL_IDENTIFIER:-placeholder}
    ports:
      - "6080-6580:6080-6580"
      - "6060:6060"
    volumes:
      - .:/code
    depends_on:
      postgis:
        condition: service_healthy

  test-production:
    image: ghcr.io/bennettoxford/openprescribing-py312-base:latest
    command: /bin/bash -c './scripts/docker_setup.sh && cd openprescribing && python manage.py check --deploy'
    environment:
      - DJANGO_SETTINGS_MODULE=openprescribing.settings.production
    ports:
      - "6080-6580:6080-6580"
      - "6060:6060"
    volumes:
      - .:/code
    depends_on:
      postgis:
        condition: service_healthy

  dev:
    image: ghcr.io/bennettoxford/openprescribing-py312-test:latest
    command: /bin/bash -c './scripts/docker_setup.sh &&  cd openprescribing && /bin/bash -l'
    environment:
      - DJANGO_SETTINGS_MODULE=openprescribing.settings.local
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      postgis:
        condition: service_healthy

volumes:
  postgis_data:
