# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-30 14:02


import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_create_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchbookmark',
            name='low_is_good',
        ),
        migrations.AddField(
            model_name='orgbookmark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 30, 14, 2, 24, 557986, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchbookmark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 30, 14, 2, 30, 426508, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
