# Generated by Django 4.2.27 on 2026-01-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0084_alter_pcn_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stp",
            name="code",
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
