# Generated by Django 4.2.27 on 2026-03-09 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0085_alter_stp_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="ncsoconcessionbookmark",
            name="pcn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="frontend.pcn",
            ),
        ),
        migrations.AddField(
            model_name="ncsoconcessionbookmark",
            name="regional_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="frontend.regionalteam",
            ),
        ),
        migrations.AddField(
            model_name="ncsoconcessionbookmark",
            name="stp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="frontend.stp",
            ),
        ),
    ]
